### ISSUE TITLE
Add ContentType HTML 

### ISSUE THREAD

**Issue by alebon** [epicallan/servant-errors#15]
Hey, thanks for the work here!

Do you mind adding text/html content type to the library? As far as I understand, it's always set to JSON? 
https://github.com/epicallan/servant-errors/blob/master/src/Network/Wai/Middleware/Servant/Errors.hs#L166

```
data Ctyp a

instance Accept (Ctyp HTML) where
  contentType _ = contentType (Proxy @HTML)

instance HasErrorBody (Ctyp HTML) '[] where
  encodeError _ _ = renderHtml $ H.div "Hello, I am an error"

errorMwHtml :: Application -> Application
errorMwHtml = errorMw @(Ctyp HTML) @'[]
```

This is what I tried. I can match on the Accept header, but it's not returned properly as a text/html response.

**Comment by epicallan** [comment]
Rendering always with JSON content type was a mistake, fixed it https://github.com/epicallan/servant-errors/pull/16 . Thanks for bringing it to my attention

Also, the Accept instance will be something like this:

```
import qualified Network.HTTP.Media as M

data HTML

instance Accept HTML where
   contentType _ = "text" M.// "html" M./: ("charset", "utf-8")
```
There is no need for wrapping it in `Ctyp` since servant doesn't provide it.

Lastly, an `HasErrorBody` for `HTML` would be very opinionated to be offered within the lib has it could take many forms. I think you should write this per your application needs, I will be happy to help if you ran into any issue while at that.

**Comment by epicallan** [comment]
PS. I have pushed an updated version 0.1.6.0 on hackage.

**Comment by alebon** [comment]
Great! Thanks a lot for the quick fix!

**Comment by epicallan** [comment]
You are welcome.
